change OpenMRS App Stage

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -28,36 +28,36 @@ jobs:
           docker compose up -d --wait
           curl -I http://localhost/openmrs/spa
 
-      - name: Wait for OpenMRS to be fully ready
+#      - name: Wait for OpenMRS to be fully ready
+#        run: |
+#
+#          echo "→ Final check: attempting login as admin (infinite retries)..."
+#
+#          while true; do
+#              SESSION=$(curl -s -X POST -d "username=admin&password=Admin123" \
+#                  http://localhost/openmrs/ws/rest/v1/session | jq -r .sessionId 2>/dev/null)
+#
+#              if [ -n "$SESSION" ] && [ "$SESSION" != "null" ]; then
+#                  echo "→ Login OK (sessionId получен) → OpenMRS ready for tests!"
+#                  exit 0
+#              fi
+#
+#              echo "Login failed! $(date +%H:%M:%S)"
+#              sleep 60
+#          done
+      - name: Wait for OpenMRS to be ready
         run: |
-
-          echo "→ Final check: attempting login as admin (infinite retries)..."
-
-          while true; do
-              SESSION=$(curl -s -X POST -d "username=admin&password=Admin123" \
-                  http://localhost/openmrs/ws/rest/v1/session | jq -r .sessionId 2>/dev/null)
-
-              if [ -n "$SESSION" ] && [ "$SESSION" != "null" ]; then
-                  echo "→ Login OK (sessionId получен) → OpenMRS ready for tests!"
-                  exit 0
-              fi
-
-              echo "Login failed! $(date +%H:%M:%S)"
-              sleep 60
-          done
-      #      - name: Wait for OpenMRS to be ready
-      #        run: |
-      #          timeout 900s bash -c '
-      #            until curl -s -f -o /dev/null http://localhost/openmrs; do
-      #              echo "Waiting backend... $(date +%H:%M:%S)"
-      #              sleep 5
-      #            done
-      #            until curl -s -f -o /dev/null http://localhost/openmrs/spa; do
-      #              echo "Waiting SPA... $(date +%H:%M:%S)"
-      #              sleep 5
-      #            done
-      #          ' || { echo "Timeout"; docker compose -f refapp/docker-compose.yml ps; exit 1; }
-      #          echo "OpenMRS ready"
+          timeout 900s bash -c '
+            until curl -s -f -o /dev/null http://localhost/openmrs; do
+              echo "Waiting backend... $(date +%H:%M:%S)"
+              sleep 5
+            done
+            until curl -s -f -o /dev/null http://localhost/openmrs/spa; do
+              echo "Waiting SPA... $(date +%H:%M:%S)"
+              sleep 5
+            done
+          ' || { echo "Timeout"; docker compose -f refapp/docker-compose.yml ps; exit 1; }
+          echo "OpenMRS ready"
 
       # ────────────────────────────────────────────────
       # Java + Maven для обоих типов тестов
